
INSERT INTO media_library (name, file_url, cover, uploaded_at) VALUES
('Document 1', 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_100KB_PDF.pdf', '#img', NOW()),
('Image 1', '#img', '#img', NOW()),
('Audio 1', NULL, '#img', NOW()),
('Document 2', 'https://freetestdata.com/wp-content/uploads/2023/07/260KB.pdf', '#img', NOW()),
('Video 1', NULL, '#img', NOW()),
('Image 2', '#img', '#img', NOW()),
('Audio 2', NULL, '#img', NOW()),
('Document 3', 'https://freetestdata.com/wp-content/uploads/2023/07/350KB.pdf', '#img', NOW()),
('Video 2', NULL, '#img', NOW()),
('Image 3', '#img', '#img', NOW()),
('Audio 3', NULL, '#img', NOW()),
('Document 4', 'https://freetestdata.com/wp-content/uploads/2023/07/412KB.pdf', '#img', NOW()),
('Video 3', NULL, '#img', NOW()),
('Image 4', '#img', '#img', NOW()),
('Audio 4', NULL, '#img', NOW()),
('Document 5', 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_500KB_PDF.pdf', '#img', NOW()),
('Video 4', NULL, '#img', NOW()),
('Image 5', '#img', '#img', NOW()),
('Audio 5', NULL, '#img', NOW()),
('Document 6', 'https://freetestdata.com/wp-content/uploads/2023/07/800KB.pdf', '#img', NOW()),
('Video 5', NULL, '#img', NOW()),
('Image 6', '#img', '#img', NOW()),
('Audio 6', NULL, '#img', NOW()),
('Document 7', 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_1MB_PDF.pdf', '#img', NOW()),
('Video 6', NULL, '#img', NOW()),
('Image 7', '#img', '#img', NOW()),
('Audio 7', NULL, '#img', NOW()),
('Document 8', 'https://freetestdata.com/wp-content/uploads/2023/07/1.5MB.pdf', '#img', NOW()),
('Video 7', NULL, '#img', NOW()),
('Image 8', '#img', '#img', NOW()),
('Audio 8', NULL, '#img', NOW()),
('Document 9', 'https://freetestdata.com/wp-content/uploads/2025/03/Free_Test_Data_2.15MB_PDF.pdf', '#img', NOW()),
('Video 8', NULL, '#img', NOW()),
('Image 9', '#img', '#img', NOW()),
('Audio 9', NULL, '#img', NOW()),
('Document 10', 'https://freetestdata.com/wp-content/uploads/2025/03/Free_Test_Data_3MB_PDF.pdf', '#img', NOW()),
('Video 9', NULL, '#img', NOW()),
('Image 10', '#img', '#img', NOW()),
('Audio 10', NULL, '#img', NOW()),
('Report 1', 'https://freetestdata.com/wp-content/uploads/2025/03/Free_Test_Data_6MB_PDF.pdf', '#img', NOW()),
('Screenshot 1', '#img', '#img', NOW()),
('Music Track 1', NULL, '#img', NOW()),
('Presentation 1', 'https://freetestdata.com/wp-content/uploads/2022/11/Free_Test_Data_10.5MB_PDF.pdf', '#img', NOW()),
('Movie Clip 1', NULL, '#img', NOW()),
('Picture 1', '#img', '#img', NOW()),
('Podcast 1', NULL, '#img', NOW()),
('Spreadsheet 1', 'https://smallpdf.com/handle-widget#url=https://assets.ctfassets.net/l3l0sjr15nav/29D2yYGKlHNm0fB2YM1uW4/8e638080a0603252b1a50f35ae8762fd/Get_Started_With_Smallpdf.pdf', '#img', NOW()),
('Short Film 1', NULL, '#img', NOW()),
('Photo 1', '#img', '#img', NOW()),
('Interview 1', NULL, '#img', NOW());
