
INSERT INTO users (name, email) VALUES
('Alice Smith', 'alice.smith@example.com'),
('Bob Johnson', 'bob.johnson@example.com'),
('Charlie Brown', 'charlie.brown@example.com'),
('Diana Miller', 'diana.miller@example.com'),
('Ethan Davis', 'ethan.davis@example.com'),
('Fiona Wilson', 'fiona.wilson@example.com'),
('George Taylor', 'george.taylor@example.com'),
('Hannah Anderson', 'hannah.anderson@example.com'),
('Isaac Thomas', 'isaac.thomas@example.com'),
('Julia Jackson', 'julia.jackson@example.com'),
('Kevin White', 'kevin.white@example.com'),
('Lily Harris', 'lily.harris@example.com'),
('Mason Martin', 'mason.martin@example.com'),
('Olivia Thompson', 'olivia.thompson@example.com'),
('Peter Garcia', 'peter.garcia@example.com'),
('Quinn Martinez', 'quinn.martinez@example.com'),
('Rachel Robinson', 'rachel.robinson@example.com'),
('Samuel Clark', 'samuel.clark@example.com'),
('Taylor Lewis', 'taylor.lewis@example.com'),
('Uma Walker', 'uma.walker@example.com'),
('Victor Hall', 'victor.hall@example.com'),
('Wendy Allen', 'wendy.allen@example.com'),
('Xavier Young', 'xavier.young@example.com'),
('Yasmine King', 'yasmine.king@example.com'),
('Zachary Wright', 'zachary.wright@example.com'),
('Amelia Green', 'amelia.green@example.com'),
('Benjamin Baker', 'benjamin.baker@example.com'),
('Charlotte Hill', 'charlotte.hill@example.com'),
('Daniel Scott', 'daniel.scott@example.com'),
('Emma Adams', 'emma.adams@example.com'),
('Frank Nelson', 'frank.nelson@example.com'),
('Grace Carter', 'grace.carter@example.com'),
('Henry Mitchell', 'henry.mitchell@example.com'),
('Isabella Perez', 'isabella.perez@example.com'),
('Jack Roberts', 'jack.roberts@example.com'),
('Katherine Turner', 'katherine.turner@example.com'),
('Liam Phillips', 'liam.phillips@example.com'),
('Mia Campbell', 'mia.campbell@example.com'),
('Noah Parker', 'noah.parker@example.com'),
('Olivia Evans', 'olivia.evans@example.com'),
('Paul Collins', 'paul.collins@example.com'),
('Quinn Stewart', 'quinn.stewart@example.com'),
('Riley Sanchez', 'riley.sanchez@example.com'),
('Sophia Morris', 'sophia.morris@example.com'),
('Thomas Rogers', 'thomas.rogers@example.com'),
('Ursula Reed', 'ursula.reed@example.com'),
('Vincent Cook', 'vincent.cook@example.com'),
('Willow Bell', 'willow.bell@example.com'),
('Xander Gray', 'xander.gray@example.com'),
('Yara Price', 'yara.price@example.com'),
('Zane Ward', 'zane.ward@example.com');

INSERT INTO orders (user_id, order_date, amount)
SELECT
    u.user_id,
    DATE '2024-01-01' + (random() * 365)::INTEGER,
    (random() * 1000)::DECIMAL(10, 2)
FROM
    users u
LIMIT 50;


-- Assuming 'orders' table exists and has data.  We'll need to insert some sample data into 'orders' first.  For simplicity, I'll assume there's an 'orders' table with at least 5 unique order_id values.

INSERT INTO order_items (order_id, product_name, quantity, price) VALUES
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Laptop', 2, 1200.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Mouse', 3, 25.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Keyboard', 1, 75.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Monitor', 1, 300.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Webcam', 2, 50.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Headphones', 1, 100.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Printer', 1, 150.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Desk', 1, 200.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Chair', 2, 100.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Tablet', 1, 300.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Smartphone', 1, 800.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Charger', 3, 20.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'External Hard Drive', 1, 80.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'USB Drive', 2, 15.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Speaker', 1, 75.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Router', 1, 60.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Modem', 1, 50.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Network Cable', 5, 5.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Software License', 1, 99.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Antivirus Software', 1, 40.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Gaming Console', 1, 400.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Video Game', 2, 60.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Controller', 1, 50.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'VR Headset', 1, 300.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Gaming Mouse', 1, 60.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Gaming Keyboard', 1, 100.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Gaming Chair', 1, 250.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'T-Shirt', 3, 25.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Jeans', 1, 50.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Shoes', 1, 75.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Socks', 2, 10.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Hat', 1, 20.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Scarf', 1, 30.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Gloves', 1, 40.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Backpack', 1, 60.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Water Bottle', 2, 15.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Coffee Maker', 1, 80.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Blender', 1, 50.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Toaster', 1, 30.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Microwave', 1, 100.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Refrigerator', 1, 800.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Oven', 1, 600.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Dishwasher', 1, 700.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Washing Machine', 1, 500.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Dryer', 1, 500.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Vacuum Cleaner', 1, 150.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Iron', 1, 40.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Ironing Board', 1, 60.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Television', 1, 500.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), 'Remote Control', 1, 20.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), '#img Photo Frame', 1, 30.00),
((SELECT order_id FROM orders ORDER BY random() LIMIT 1), '#pdf User Manual', 1, 0.00);
