
INSERT INTO order_items (order_id, product_name, quantity, price) VALUES
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Laptop', 2, 1200.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Mouse', 3, 25.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Keyboard', 1, 75.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Monitor', 1, 300.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Webcam', 2, 50.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Headphones', 1, 100.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'External Hard Drive', 1, 80.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'USB Drive', 4, 15.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Printer', 1, 150.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Scanner', 1, 100.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Office Chair', 1, 200.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Desk', 1, 180.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Smartphone', 1, 800.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Tablet', 1, 300.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Smartwatch', 1, 200.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Charger', 2, 20.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Phone Case', 1, 15.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Screen Protector', 1, 10.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Wireless Router', 1, 60.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'HDMI Cable', 3, 12.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Ethernet Cable', 2, 10.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Laptop Bag', 1, 30.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Power Bank', 2, 25.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Bluetooth Speaker', 1, 50.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'SD Card', 3, 20.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'External SSD', 1, 90.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Gaming Mouse', 1, 60.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Gaming Keyboard', 1, 80.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Graphics Card', 1, 400.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'CPU', 1, 300.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'RAM', 2, 70.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Motherboard', 1, 150.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'SSD', 1, 120.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Case Fan', 3, 15.00),
  ((SELECT order_id FROM orders ORDER BY RANDOM() LIMIT 1), 'Power Supply', 1, 100.00);
